# Generated by Django 5.0.2 on 2024-07-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
